core/urls.py
from django.contrib import admin
from django.urls import include, path

import school_test.views

urlpatterns = [
    path("admin/", admin.site.urls),
    path("school_test/", include("school_test.urls")),
    path("", school_test.views.user_login),
]

school_test/urls.py
from django.urls import path

import school_test.views

app_name = "school_test"

urlpatterns = [
    path("login/", school_test.views.user_login, name="login"),
    path("logout/", school_test.views.user_logout, name="logout"),
    path("validate_user/", school_test.views.user_login_validate, name="validate"),
    path("result/", school_test.views.result_calculate, name="result"),
    path("home/", school_test.views.home, name="home"),
    path("home/prova/<int:id_test>", school_test.views.student_test, name="test"),
    # path("<int:id_student>/test/", school_test.views.home, name="home"),
]

school_test/models.py
import datetime

from argon2 import PasswordHasher
from django.contrib.auth.hashers import make_password
from django.contrib.auth.models import User
from django.db import models
from django.db.models.signals import pre_save
from django.utils.timezone import now


# Questao(Id_Questão,Texto, Op1, Op2, Op3, Op4, Materia, data, Dificuldade, Resposta)
class Question(models.Model):
    question_text = models.CharField(max_length=2000, null=False)
    create_date = models.DateTimeField(default=now, editable=False)

    op1 = models.CharField(max_length=500, null=False)
    op2 = models.CharField(max_length=500, null=False)
    op3 = models.CharField(max_length=500, null=False)
    op4 = models.CharField(max_length=500, null=False)

    question_subject = models.CharField(max_length=10, null=False)
    answer = models.IntegerField(null=False)

    def __str__(self):
        return f"{self.question_text} | {self.question_subject} |Dif {self.difficulty_level}"


# Prova(Id_Prova, Nome_Prova ,Materia)
class ReadyTest(models.Model):
    test_name = models.CharField(max_length=200, null=False)
    subject = models.CharField(max_length=10, null=False)
    test_descripition = models.CharField(max_length=500)

    def __str__(self):
        return f"Prova : {self.test_name}"


class TestQuestions(models.Model):
    id_question = models.ForeignKey(Question, on_delete=models.CASCADE)
    id_test = models.ForeignKey(ReadyTest, on_delete=models.CASCADE)

    def __str__(self):
        return f"Questão : {self.id_question} → {self.id_test}"


# ParaFazer(Id_Aluno, Id_Prova)
class TestToDo(models.Model):
    id_student = models.ForeignKey(User, on_delete=models.CASCADE)
    id_test = models.ForeignKey(ReadyTest, on_delete=models.CASCADE)
    was_done = models.BooleanField(null=False, default=False)
    grade = models.FloatField(null=False, default=0)

    def __str__(self):
        return f"{self.id_student} → {self.id_test}"


def make_password_hasher(sender, instance, **kwargs):
    if not instance.id:
        hash = make_password(instance.password)
        instance.password = hash
    else:
        current_instance = sender.objects.get(id=instance.id)
        if current_instance.password != instance.password:
            hash = make_password(instance.password)
            instance.password = hash


# Conecta a função ao sinal pre_save
pre_save.connect(make_password_hasher, sender=User)

school_test/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import redirect, render
from django.urls import reverse

from .models import TestToDo
from .utils import build_data_of_pages as build_data
from .utils import calculate_test_result as calculate_test


def user_login(request) -> HttpResponse:
    return render(request, "school_test/login.html")


def user_login_validate(request) -> HttpResponseRedirect:
    try:
        username = request.POST["username"]
        password = request.POST["password"]

        user = authenticate(request, username=username, password=password)

        if user == None:
            raise Exception("wrong username or passoword")

    except Exception as err:
        print(f"Login Erro : {err}")
        return redirect(reverse("school_test:login"))
    else:
        request.session["user_id"] = user.id
        login(request, user)
        return redirect(reverse("school_test:home"))


@login_required(login_url="/school_test/login/")
def home(request) -> HttpResponse:
    context = {
        "student_tests": build_data.build_list_of_tests(
            request.session.get("user_id", None)
        )
    }
    return render(request, "school_test/home.html", context, status=200)


@login_required(login_url="/school_test/login/")
def student_test(request, id_test: int) -> HttpResponse:
    try:
        id_student = request.session.get("user_id", None)
        context = {"test": build_data.build_student_test(id_student, id_test)}
    except TestToDo.DoesNotExist as cont_not_exist:
        print(f" Erro, student test not finded : {cont_not_exist}")
        return redirect(reverse("school_test:home"))
    else:
        return render(request, "school_test/test.html", context, status=200)


@login_required(login_url="/school_test/login/")
def result_calculate(request) -> HttpResponseRedirect:
    try:
        grade = calculate_test.calculate_test_grade(
            calculate_test.remove_identification_data(request.POST)
        )
        calculate_test.regist_student_test_grade(request.POST, grade)
    except Exception as err:
        print(f"Result Erro : {err}")
        calculate_test.enable_student_to_make_the_test(request.POST, grade)
    finally:
        return redirect(reverse("school_test:home"))


def user_logout(request) -> HttpResponseRedirect:
    logout(request=request)
    return redirect(reverse("school_test:login"))

school_test/templates/school_test/home.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
     integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
     <title>Home</title>
</head>
<body>
     <header>
          <nav class="navbar bg-dark border-bottom border-body" data-bs-theme="dark">
               <div class="container-fluid">
                    <a class="navbar-brand" href="">Provas Escolares de {{student_tests.name_student}} </a>
                    <a class="navbar-brand" href="{% url 'school_test:logout' %}">Sair</a>
               </div>
          </nav>
     <header>
     
     {% if student_tests %}
          <table class="table table-striped">
               {% for test in student_tests.associated_tests %}
                    <tr>
                         {% if test.was_done %}
                              <td>{{ test.test_name }}</td>
                              <td>{{test.grade}}</td>
                         {% else %}
                              <td><a class="link-success link-offset-2 link-underline link-underline-opacity-25"  href="prova/{{test.id}}" >{{ test.test_name }}<a></td>
                              <td> Não feito </td>
                         {% endif %}
                    <tr>
               {% endfor %}
          </table>
     {% else %}
     <p>Não há testes para serem feitos.</p>
     {% endif %}
</body>
</html>

school_test/templates/school_test/login.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <link
      rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css"
      integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN"
      crossorigin="anonymous"
    />
    <title>Login</title>
  </head>
  <body>
    <form
      class="d-flex justify-content-center my-5"
      action="{% url 'school_test:validate' %}"
      method="post"
    >
      <div class="w-50 border rounded border-dark p-5">
        <legend>Login de Aluno</legend>
        <fieldset>
          {% csrf_token %} {% if error_message %}
          <div class="alert alert-danger" role="alert">{{ error_message }}</div>
          {% endif %}
          <div class="form-outline mb-4">
            <label class="form-label" for="username">Nome de Usuário: </label>
            <input
              class="form-control"
              id="username"
              type="text"
              name="username"
              value="{{current_id}}"
            />
          </div>
          <div class="form-outline mb-4">
            <label class="form-label" for="password">Senha: </label>
            <input
              class="form-control"
              id="password"
              type="password"
              name="password"
              value="{{current_password}}"
            />
          </div>
          <input class="btn btn-primary" type="submit" value="Login" />
        </fieldset>
      </div>
    </form>
  </body>
</html>

school_test/templates/school_test/test.html
<!DOCTYPE html>
<html lang="en">
<head>
     <meta charset="UTF-8">
     <meta name="viewport" content="width=device-width, initial-scale=1.0">
     <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" 
integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
     <title>Prova</title>
</head>
<body>
     <div class="mx-5">
          <h1>{{test.name}}</h1>
          <h3>{{test.subject}}</h3>
          <div>
               <p>Aluno : {{test.name_student}}</p>
          </div>
          <form action="{% url 'school_test:result' %}" method="post">
               </fieldset>
                    <input type="hidden" id="id_studet" name="id_student" value="{{test.id_student}}">
                    <input type="hidden" id="id_test" name="id_test" value="{{test.id_test}}">
                    {% csrf_token %}
                    {% for question in test.questions %}
                         <hr>
                         <legend>{{question.question_text}}</legend>
                         <div class="mb-3">
                              <input class="btn btn-outline-success" type="radio" name="{{question.id}}" id="question{{ forloop.counter }}" value="1"/>
                              <label class="form-label" for="opt1">{{question.op1}}</label>
                         </div>
                         <div class="mb-3">
                              <input class="btn btn-outline-success" type="radio" name="{{question.id}}" id="question{{ forloop.counter }}" value="2"/>
                              <label class="form-label" for="opt2">{{question.op2}}</label>
                         </div >
                         <div class="mb-3">
                              <input class="btn btn-outline-success" type="radio" name="{{question.id}}" id="question{{ forloop.counter }}" value="3"/>
                              <label class="form-label" for="opt3">{{question.op3}}</label>
                         </div >
                         <div class="mb-3">
                              <input class="btn btn-outline-success" type="radio" name="{{question.id}}" id="question{{ forloop.counter }}" value="4"/>
                              <label class="form-label" for="opt4">{{question.op4}}</label>
                         </div >
                    {% endfor %}
                    <hr>
                    <input class="btn btn-primary" type="submit" value="Concluir">
               </fieldset>
          </form>
     </div>     
</body>
</html>